@startuml

 namespace de.gematik.ti.fdv.android.epa.service.localization {
    class de.gematik.ti.fdv.android.epa.service.localization.GatewayModulePathType {
        - path : String
        - ttl : long
        - validUntil : Date
        + GatewayModulePathType()
        + getPath()
        + getValidUntil()
    }
  }


  namespace de.gematik.ti.fdv.android.epa.service.localization {
    class de.gematik.ti.fdv.android.epa.service.localization.ServiceLocator {
        {static} - LOG : Logger
        {static} - MAX_LOOKUP_PER_MINUTE : int
        {static} - ONE_MINUTE_MILLIS : long
        {static} - PORT : int
        {static} - SCHEME : String
        - dnsTxtRecordValues : Map<String, GatewayModulePathType>
        - executor : Executor
        - fqdn : String
        - lookupFailureCount : int
        - lookupFailureDate : Date
        - lookupStatus : LookupStatus
        - records : Record[]
        - running : boolean
        + ServiceLocator()
        + ServiceLocator()
        + endpointURLForInterface()
        + getHomeCommunityID()
        + getLookupStatus()
        + lookup()
        - checkExecutor()
        - checkLookupFailureTimeRange()
        - checkTxtVersion()
        - conditionalLookup()
        - fillDnsTxtRecordValues()
        - fillModuleList()
        - handleLookupFailure()
        - handleTTL()
    }
  }

  de.gematik.ti.fdv.android.epa.service.localization.ServiceLocator .up.|> de.gematik.ti.fdv.epa.service.localization.spi.IServiceLocalizer

@enduml